### PR TITLE
Enable multiple runs

### LINKED ISSUE #1: Enable multiple runs
Update the sample/main.rs script to:

- run several iterations with a specified model, prompt and number of tokens
- estimate and log tokens/second

### PR DESCRIPTION
**Pull request by nsosio**
Fixes #1

### CODE REVIEW

**Review by filopedraz — APPROVED** [review]
I suggest that afterwards you create a PR to the source repositories too :)

**Review by biswaroop1547 — APPROVED** [review]
lgtm

**Comment by nsosio** [comment]
> I suggest that afterwards you create a PR to the source repositories too :)

Yep, I'll also create a PR to the source repo :)

**Comment by nsosio** [comment]
Added PR to source repo https://github.com/Gadersd/llama2-burn/pull/8

**Pull request merged**
